name: Criar APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
-uses: actions/chekout#v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
     - name: Definir ANDROID_HOME  
        run: echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        
     - name: Instalar Android SDK Command-Line Tools
  run: |
    mkdir -p $ANDROID_HOME/cmdline-tools
    wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
    unzip -q cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
    mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
    echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
    echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
      - name: Aceitar licen√ßas e instalar AIDL  
        run: |  
          sudo apt update  
          sudo apt install -y android-sdk aidl  
          yes | sudo sdkmanager --licenses  
          sudo sdkmanager "build-tools;36.1.0"
          
          pip install cython buildozer
      - name: Build APK
        run: |
          buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: lmarena-apk
          path: bin/*.apk
