on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Instalar buildozer e Cython
        run: |
          pip install --upgrade pip
          pip install cython
          pip install buildozer

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
  
      - name: Definir ANDROID_HOME  
        run: echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Instalar Android SDK Command-Line Tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Aceitar licenÃ§as e instalar build-tools 36.1.0
        run: |
          mkdir -p $ANDROID_SDK_ROOT/licenses
          echo 8933bad161af4178b1185d1a4f832955c8f7e23f > $ANDROID_SDK_ROOT/licenses/android-sdk-license
          echo d56f5187479451eabf01fb78af6dfcb131a6481e >> $ANDROID_SDK_ROOT/licenses/android-sdk-license
          echo 24333f8a63b6825ea9c5514f83c2829b004d1fee >> $ANDROID_SDK_ROOT/licenses/android-sdk-license
          echo 84831b9409646a918e30573bab4c9c91346d8abd >> $ANDROID_SDK_ROOT/licenses/android-sdk-license
          sdkmanager --install "build-tools;36.1.0" --sdk_root=$ANDROID_SDK_ROOT
          echo "$ANDROID_SDK_ROOT/build-tools/36.1.0" >> $GITHUB_PATH
      - name: Lista tudo que existe em build-tools/36.1.0
        run: ls -la $ANDROID_SDK_ROOT/build-tools/36.1.0    
      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: lmarena-apk
          path: bin/*.apk

